/// Flutter icons TryMeIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TryMeIcons
///      fonts:
///       - asset: fonts/TryMeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TryMeIcons {
  TryMeIcons._();

  static const _kFontFam = 'TryMeIcons';
  static const String? _kFontPkg = null;

  static const IconData addFriends = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calander = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorates = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlocked = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userCard = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
